version: "3.9"
services:
  react:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web/:/app/web/
    env_file:
      - ./web/.env.prod
    depends_on:
      - django
    networks:
      - app-network 
    container_name: memoryrush-react-frontend-container


  django:
    build:
      context: ./api/
      dockerfile: Dockerfile
    # ports:
    #  - "8000:8000"
    volumes:
      - ./api/:/app/api/
    env_file:
      - ./api/.env.prod  # Load environment variables from the .env.prod file
    depends_on:
      - redis # Ensure Redis starts before the Django service
    networks:
      - app-network
    container_name: memoryrush-django-backend-container
    
  
  redis:
    image: redis:7
    # ports:
    #  - "6379:6379"
    networks:
        - app-network
    container_name: memoryrush-redis-container

networks:
  app-network:
    driver: bridge